### ISSUE TITLE
[O21] Forgotten Realms Prevents Mod Settings From Appearing

### ISSUE THREAD

**Issue by mikester112** [Solid-Wires/rimworldmod-pawnkindracediversification#12]
https://steamcommunity.com/sharedfiles/filedetails/?id=2184183669

Forgotten Realms prevents the mod settings menu from Pawnkind Race Diversification from appearing. 

Easily reproducible by running the game with the only mods enabled being this, Forgotten Realms and all their prerequisites.

**Comment by Solid-Wires** [comment]
Oh, interesting. Will have to look into this.

**Comment by Solid-Wires** [comment]
Oops, my bad. Should have had a null reference exception on checking the filename of the alien def.
I could have fixed this _really_ quickly, but I was really tired and I had to rest several times today. I apologize for that.
You see, the problem was that these alien races added from that mod do not have XML file paths, as they are probably hardcoded. I should have seen that as a possibility.

Beware though, because looking at this mod, it sounds like it tried to do what this mod does with its own races exclusively. I suggest either disable Race Integration in its mod settings in order to use the weight adjustments from this mod instead or keep it enabled and leave the weight adjustments in those races alone as -1 (or 0 if you want to be sure). These races are indicated as O21 races listed under this mod's settings.
